{
 "title": "Falkor DB",
 "tags": [
  "database",
  "graph"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"redis-exporter:9121\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process Id",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_process_id{instance=\"redis-exporter:9121\", job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "connected clients ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"redis-exporter:9121\"}"
    }
   ]
  },
  {
   "title": "FalkorDB Restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "falkordb_restarts_total", "legendFormat": "restarts" }
   ]
  },
  {
   "title": "calls / sec ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"redis-exporter:9121\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(redis_commands_latencies_usec_count[1m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"redis-exporter:9121\"} ",
     "legendFormat": "redis_memory_used_bytes"
    }
   ]
  },
  {
   "title": "waiting requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "falkordb_waiting_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "redis_last_slow_execution_duration_seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_last_slow_execution_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "running requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "falkordb_running_requests", "legendFormat": "__auto" }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "queries/sec (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (rate(operations_total{vendor=\"falkor\"}[1m]))",
     "legendFormat": "executor {{spawn_id}}"
    }
   ]
  },
  {
   "title": "queries/sec (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor, spawn_id)  (rate(operations_total{vendor=\"falkor\"}[1m]))",
     "legendFormat": "executor {{spawn_id}}"
    }
   ]
  },
  {
   "title": "number of nodes in the graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "falkordb_nodes_total", "legendFormat": "nodes number" }
   ]
  },
  {
   "title": "number of relationships in the graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "falkordb_relationships_total", "legendFormat": "relationships number" }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (operations_error_total{vendor=\"falkor\"}) or vector(0)",
     "legendFormat": "all errors"
    }
   ]
  },
  {
   "title": "Successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor) (operations_total{vendor=\"falkor\"}) - sum by (vendor) (operations_error_total{job=\"falkor_benchmark\"}) or (sum by (vendor) (operations_total{vendor=\"falkor\"}) )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}