{
 "title": "neo4j",
 "tags": [
  "graph",
  "database",
  "benchmark"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor) (operations_total{vendor=\"neo4j\"}) - sum by (vendor) (operations_error_total{job=\"falkor_benchmark\"}) or (sum by (vendor) (operations_total{vendor=\"neo4j\"}) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (operations_error_total{vendor=\"neo4j\"}) or vector(0)",
     "legendFormat": "all errors"
    }
   ]
  },
  {
   "title": "queries/sec (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (rate(operations_total{vendor=\"neo4j\"}[1m]))",
     "legendFormat": "executor {{spawn_id}}"
    }
   ]
  },
  {
   "title": "queries/sec (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor, spawn_id)  (rate(operations_total{vendor=\"neo4j\"}[1m]))",
     "legendFormat": "executor {{spawn_id}}"
    }
   ]
  },
  {
   "title": "neo4j_msg_deadline_offset_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "neo4j_msg_deadline_offset", "legendFormat": "neo4j_msg_deadline_offset" }
   ]
  },
  {
   "title": "percentile successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(neo4j_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(neo4j_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(neo4j_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 99"
    }
   ]
  }
 ]
}